FROM golang:1.14-alpine as builder
ENV GO111MODULE=on
ADD algorand-claimer /algorand-claimer
WORKDIR /algorand-claimer
RUN go build

FROM golang:1.14-alpine
COPY --from=builder /algorand-claimer/algorand-claimer .
ADD algorand-claimer/sync_node.sh /
ENTRYPOINT [ "sync_node.sh && ./algorand-claimer" ]
