version: '3'
services:
  algorand-algod:
    image: algorand-algod:${VERSION}
    build:
      context: algod
      dockerfile: Dockerfile.algod
      args:
        CHANNEL: "${ALGOD_CHANNEL}"
        URL: "${ALGOD_URL}"
        BRANCH: "${ALGOD_BRANCH}"
        SHA: "${ALGOD_SHA}"
        BOOTSTRAP_URL: "${NETWORK_BOOTSTRAP_URL}"
        GENESIS_FILE: "${NETWORK_GENESIS_FILE}"
        TOKEN: ${TOKEN}
        ALGOD_PORT: "${ALGOD_PORT}"
        KMD_PORT: "${KMD_PORT}"
        ALGORAND_DATA: "${ALGORAND_DATA_CONTAINER_MOUNT}"
  algorand-claimer:
    image: algorand-claimer:${VERSION}
    build:
      context: claimer
      dockerfile: Dockerfile.claimer
