---
apiVersion: v1
kind: Namespace
metadata:
  name: "algorand"
  labels:
    name: "algorand"
---
apiVersion: batch/v1
kind: Job
metadata:
 name: algorand-claimer-algod
 namespace: algorand
spec:
 template:
   metadata:
     name: algorand-claimer
   spec:
     restartPolicy: "Never"
     initContainers:
     - name: volume-permissions
       image: busybox
       command: ['sh', '-c', 'chown -R 1000:1000 ${ALGORAND_DATA_CONTAINER_MOUNT}']
       volumeMounts:
       - mountPath: ${ALGORAND_DATA_CONTAINER_MOUNT}
         name: host-mount
     containers:
     - name: algod
       image: algorand-algod:${VERSION}
       env:
         - name: CATCHPOINT_BLOCK_DRIFT_THRESHOLD
           value: "${CATCHPOINT_BLOCK_DRIFT_THRESHOLD}"
         - name: ALGORAND_CLAIMER_ALGOD_PORT
           value: "${ALGORAND_CLAIMER_ALGOD_PORT}"
         - name: ALGORAND_CLAIMER_ALGOD_TOKEN
           value: "${ALGORAND_CLAIMER_ALGOD_TOKEN}"
         - name: SHUTDOWN_PORT
           value: "${SHUTDOWN_PORT}"
       volumeMounts:
       - mountPath: ${ALGORAND_DATA_CONTAINER_MOUNT}
         name: host-mount
     - name: claimer
       image: algorand-claimer:${VERSION}
       env:
         - name: SHUTDOWN_PORT
           value: "${SHUTDOWN_PORT}"
         - name: ALGORAND_CLAIMER_HOST
           value: "${ALGORAND_CLAIMER_HOST}"
         - name: ALGORAND_CLAIMER_ALGOD_PORT
           value: "${ALGORAND_CLAIMER_ALGOD_PORT}"
         - name: ALGORAND_CLAIMER_ALGOD_TOKEN
           value: "${TOKEN}"
         - name: ALGORAND_CLAIMER_KMD_PORT
           value: "${ALGORAND_CLAIMER_KMD_PORT}"
         - name: ALGORAND_CLAIMER_KMD_TOKEN
           value: "${TOKEN}"
         - name: ALGORAND_CLAIMER_MIN_CLAIM_AMOUNT
           value: "${ALGORAND_CLAIMER_MIN_CLAIM_AMOUNT}"
         - name: ALGORAND_CLAIMER_WALLET_NAME
           value: "${ALGORAND_CLAIMER_WALLET_NAME}"
         - name: ALGORAND_CLAIMER_PASSPHRASE
           valueFrom:
             secretKeyRef:
               name: algorand-claimer-secret
               key: passphrase
         - name: ALGORAND_CLAIMER_MNEMONIC
           valueFrom:
             secretKeyRef:
               name: algorand-claimer-secret
               key: mnemonic
     volumes:
     - name: host-mount
       hostPath:
         path: ${ALGORAND_DATA_HOST_MOUNT}
---
apiVersion: v1
kind: Secret
metadata:
  name: algorand-claimer-secret
  namespace: algorand
type: Opaque
data:
  mnemonic: |
    ${ALGORAND_MNEUMONIC}
  passphrase: |
    ${ALGORAND_CLAIMER_PASSPHRASE}
